CC = g++
CFLAGS = -g -Wall -Weffc++ -std=c++11
LFLAGS = -L/usr/lib


# All Targets

all: warehouse


# Tool invocations

# Executable "hello" depends on the files hello.o and run.o.

warehouse: clean bin/WareHouse.o bin/Action.o bin/Order.o bin/Volunteer.o bin/Customer.o bin/main.o

	@echo 'Building target: Src'

	@echo 'Invoking: C++ Linker'

	$(CC) -o bin/warehouse bin/WareHouse.o bin/Action.o bin/Order.o bin/Volunteer.o bin/Customer.o bin/main.o $(LFLAGS)

	@echo 'Finished building target: warehouse'

	@echo ' '



bin/main.o: src/main.cpp

	$(CC) $(CFLAGS) -c -Iinclude -o bin/main.o src/main.cpp

bin/WareHouse.o: src/WareHouse.cpp

	$(CC) $(CFLAGS) -c -Iinclude -o bin/WareHouse.o src/WareHouse.cpp

bin/Action.o: src/Action.cpp

	$(CC) $(CFLAGS) -c -Iinclude -o bin/Action.o src/Action.cpp

bin/Customer.o: src/Customer.cpp

	$(CC) $(CFLAGS) -c -Iinclude -o bin/Customer.o src/Customer.cpp

bin/volunteer.o: src/volunteer.cpp

	$(CC) $(CFLAGS) -c -Iinclude -o bin/Volunteer.o src/Volunteer.cpp

bin/Order.o: src/Order.cpp

	$(CC) $(CFLAGS) -c -Iinclude -o bin/Order.o src/Order.cpp


#Clean the build directory

clean:

	rm-f bin/*